remote_theme: pages-themes/architect@v0.2.0
title: Ruang Belajar - Sistem Informasi
description: Repositori perkuliahan Sistem Informasi @ STMIM Mardira Indonesias

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one