title: testing midnight theme...
email: email@example.com
description: ...description...
domain: pujangga123.github.io
url: http://pujangga123.github.io
github_username:  pujangga123

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
